name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  autofix:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm format

      - name: Run autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          fail-fast: false
